apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    type: proxy
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    type: proxy


